---
baseURL: https://tesblog.netlify.app/
languageCode: en-us
title: Ferilee
theme: piko
paginate: "5"
copyright: A template by [Heksagon](https://www.heksagon.net "Your most friendly developer")
googleAnalytics: 
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false
params:
  analytics:
    google:
      SiteVerificationTag: 
    yandex:
      SiteVerificationTag: 
    bing:
      SiteVerificationTag: 
  env: production
  author: Ferilee
  description: Portofolio Ferilee | Pengajar Praktik PGP Angkatan 5 Kabupaten Lumajang
  math: true
  images:
  - "/uploads/og.webp"
  label:
    title: Ferilee
    text: Welcome to Piko
    icon: "/uploads/zap.svg"
    iconHeight: "35"
    iconWIdth: "35"
  comments: true
  mainSections:
  - blog
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: "/legal/privacy/#cookies-and-web-beacons"
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: 
  assets:
    disableFingerprinting: false
    favicon: "/uploads/zap.svg"
    favicon16x16: "/uploads/zap.svg"
    favicon32x32: "/uploads/zap.svg"
    apple_touch_icon: "/uploads/zap.svg"
    safari_pinned_tab: "/uploads/zap.svg"
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    disableHeroSection: false
    heroUpperTitle: 
    heroTitle: Ferilee
    heroDescription: Pengajar Praktik PGP Angkatan 5 Kabupaten Lumajang
    heroCTAPrimaryText: Blog
    heroCTAPrimaryUrl: "/blog/"
    heroCTASecondaryText: Contact Me
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "/uploads/portfolio-0.webp"
    disableBlogSection: true
    blogTitle: Latest Posts
    blogDescription: This is my latest blog posts
    seeMoreText: More Posts
    disableAboutSection: false
    aboutTitle: About
    aboutDescription: Ferilee
    aboutImgUrl: "/uploads/png_20221023_093251_0000.png"
    aboutContent: Feri Dwi Hermawan. Seorang guru matematika yang gemar mempelajari
      dunia digital. Akrab dipanggil dengan sebutan ferilee sejak kuliah dulu, karena
      menyukai bela diri hehehehee … Aktif di beberapa komunitas digital seperti Indonesia
      Digital Teacher, Matematika Nusantara, dan menyukai channel seperti GimpScape.
    disablePortfolioSection: false
    portfolioTitle: Portfolio
    portfolioDescription: Some of my works
    portfolio:
    - imageUrl: "/uploads/portfolio-1.webp"
      alt: 
      description: Portfolio One.
      websiteUrl: 
    - imageUrl: "/uploads/portfolio-2.webp"
      alt: 
      description: Portfolio Two.
      websiteUrl: 
    - imageUrl: "/uploads/portfolio-3.webp"
      alt: 
      description: Portfolio Three.
      websiteUrl: 
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
menus:
  main:
  - name: Aksi
    title: Artefak Aksi Nyata
    pre: activity
    url: "/aksinyata"
    weight: "21"
  - name: Kursus dan Sertifikat
    title: Kursus dan Sertifikat
    pre: award
    url: "/sertifikat"
    weight: "22"
  - name: Publikasi
    title: Publikasi
    pre: upload
    url: "/publikasi"
    weight: "23"
  - name: Umpan Balik
    title: Umpan Balik
    pre: message-square
    url: "/feedback"
    weight: "24"
  - name: Search
    title: Search
    pre: search
    url: "/search"
    weight: "30"
  search:
  - name: Categories
    title: Categories
    url: "/categories"
    weight: "10"
  - name: Archives
    title: Archives
    url: "/archives"
    weight: "20"
  - name: Tags
    title: Tags
    url: "/tags"
    weight: "30"
